server:
  port:
    ${API_GATEWAY_PORT}

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: SERVICE-SEARCH
          uri: http://localhost:${SERVICE_SEARCH_PORT}
          predicates:
            - Path=/service-search/api/search/**